### PR TITLE
:car: add react-router, alias, style

### PR DESCRIPTION
**Pull request by alex-wilmer**
- update readme
- add webpack aliases for components, style
- use `js` instead of `jsx`
- import style index
- create two basic routes and pass down state, props, functions

### CODE REVIEW

**Comment by Sailias** [comment]
@alex-wilmer great PR.  Do you think we should put it into master or a new 'react-router' branch?  I can create that branch on this project and you can submit that PR to that branch.

**Comment by alex-wilmer** [comment]
Probably a branch for now.. I think after it gets some use / feedback we can consider if it's better off as the main branch. Should update the readme on master to inform students of a router branch for single page apps.

**Comment by Sailias** [comment]
@alex-wilmer I agree.  I'll add your README enhancements into master.  Unfortunately that means you'll have to resubmit your PR as I can't change it's target.

**Comment by alex-wilmer** [comment]
https://github.com/lighthouse-labs/webpack-react-skeleton/pull/2

**Pull request closed without merging**
